language: csharp
mono: latest
dotnet: 2.1.105
solution: Tensor/Tensor.sln
before_install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update -q
  - sudo apt-get install -y powershell
install:
  - echo '<?xml version="1.0" encoding="utf-8"?>' > NuGet.Config
  - echo '<configuration><packageSources>' >> NuGet.Config
  - echo '<add key="CorePorts" value="https://www.myget.org/F/coreports/api/v3/index.json" protocolVersion="3" />' >> NuGet.Config
  - echo '</packageSources></configuration>' >> NuGet.Config
script: 
  - unset DOTNET_CLI_TELEMETRY_OPTOUT
  - VER=$(cat Revision.targets | egrep -o '[0-9]+')
  - if [ "$TRAVIS_BRANCH" != "master" ]; then echo "<Project><PropertyGroup><Rev>$VER-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER</Rev></PropertyGroup></Project>" > Revision.targets; fi
  - dotnet build -c Release Tensor/Tensor.sln
  - dotnet test -c Release Tensor/Tensor.Test/Tensor.Test.fsproj
  - dotnet pack -c Release Tensor/Tensor.sln
  - pwsh Tensor/Tensor.Docs/Build.ps1
after_success:
  - dotnet nuget push -s https://www.myget.org/F/coreports/api/v2/package -k $MYGETKEY 'Packages/Release/*.nupkg' || true
  - if [ "$TRAVIS_BRANCH" = "master" ]; then git clone https://github.com/DeepMLNet/webpage.git; rm -rf webpage/.git webpage/Tensor; cp -av Tensor/Tensor.Docs/_site/ webpage/Tensor; fi
deploy:
  provider: pages
  local-dir: webpage
  repo: DeepMLNet/webpage
  fqdn: www.deepml.net
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  on:
    branch: master