language: csharp
mono: none
dotnet: 2.0.0
solution: DeepNet.sln
install:
  - mkdir -p ~/.nuget/NuGet
  - echo '<?xml version="1.0" encoding="utf-8"?>' > ~/.nuget/NuGet/NuGet.Config
  - echo '<configuration><packageSources>' >> ~/.nuget/NuGet/NuGet.Config
  - echo '<add key="Core Ports" value="https://www.myget.org/F/coreports/api/v3/index.json" protocolVersion="3" />' >> ~/.nuget/NuGet/NuGet.Config
  - echo '<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />' >> ~/.nuget/NuGet/NuGet.Config
  - echo '</packageSources></configuration>' >> ~/.nuget/NuGet/NuGet.Config
script: 
  - dotnet build
  - pushd Numeric/TensorTests
  - dotnet xunit
  - popd
  - dotnet pack -c Release


