Data:
  Path: abalone.txt
  TargetCols: [8]
Network:
  Type: GPTransfer
  Name: GPTU
  Layers: 1
  Layer1:
    Hyperpars:
      NInput: 8
      NGPs: out
      NTrnSmpls: 20
Training:
  Device: DevCuda
  Opt:
    Optimizer: Adam
    Congif: default
  Loss: CrossEntropy
  Config: default
